"""Static alias dictionary mapping common variants to canonical names."""

ALIAS_DICT: dict[str, str] = {
    # AI products
    "chatgpt": "ChatGPT",
    "gpt": "ChatGPT",
    "chat gpt": "ChatGPT",
    "gpt-4": "ChatGPT",
    "gpt4": "ChatGPT",
    "openai": "OpenAI",
    "open ai": "OpenAI",
    "claude": "Claude",
    "anthropic": "Anthropic",
    "gemini": "Gemini",
    "bard": "Gemini",
    "google bard": "Gemini",
    "copilot": "GitHub Copilot",
    "github copilot": "GitHub Copilot",
    "midjourney": "Midjourney",
    "mid journey": "Midjourney",
    "stable diffusion": "Stable Diffusion",
    "stablediffusion": "Stable Diffusion",
    "dall-e": "DALL-E",
    "dalle": "DALL-E",
    # Gaming
    "steam deck": "Steam Deck",
    "steamdeck": "Steam Deck",
    "nintendo switch": "Nintendo Switch",
    "switch 2": "Nintendo Switch 2",
    "ps5": "PlayStation 5",
    "playstation 5": "PlayStation 5",
    "playstation5": "PlayStation 5",
    "xbox": "Xbox",
    "xbox series x": "Xbox Series X",
    # Tech companies
    "apple": "Apple",
    "google": "Google",
    "microsoft": "Microsoft",
    "meta": "Meta",
    "facebook": "Meta",
    "amazon": "Amazon",
    "netflix": "Netflix",
    "tesla": "Tesla",
    "nvidia": "NVIDIA",
    "amd": "AMD",
    "intel": "Intel",
    "samsung": "Samsung",
    # Apps / services
    "tiktok": "TikTok",
    "tik tok": "TikTok",
    "instagram": "Instagram",
    "insta": "Instagram",
    "twitter": "X (Twitter)",
    "x.com": "X (Twitter)",
    "threads": "Threads",
    "spotify": "Spotify",
    "youtube": "YouTube",
    "yt": "YouTube",
    "discord": "Discord",
    "slack": "Slack",
    "notion": "Notion",
    "figma": "Figma",
    # Korean brands
    "삼성": "Samsung",
    "삼성전자": "Samsung",
    "lg": "LG",
    "엘지": "LG",
    "엘지전자": "LG",
    "현대": "Hyundai",
    "hyundai": "Hyundai",
    "현대자동차": "Hyundai",
    "카카오": "Kakao",
    "kakao": "Kakao",
    "카카오톡": "Kakao",
    "카톡": "Kakao",
    "네이버": "Naver",
    "naver": "Naver",
    "쿠팡": "Coupang",
    "coupang": "Coupang",
    "토스": "Toss",
    "toss": "Toss",
    "당근": "Karrot",
    "당근마켓": "Karrot",
    "karrot": "Karrot",
    # Crypto
    "비트코인": "Bitcoin",
    "bitcoin": "Bitcoin",
    "btc": "Bitcoin",
    "이더리움": "Ethereum",
    "ethereum": "Ethereum",
    "eth": "Ethereum",
    "솔라나": "Solana",
    "solana": "Solana",
    "sol": "Solana",
    # Food / lifestyle trends
    "오픈런": "Open Run",
    "open run": "Open Run",
    "open_run": "Open Run",
    "품절": "Sold Out",
    "sold out": "Sold Out",
    "sold_out": "Sold Out",
    # Entertainment / streaming
    "넷플릭스": "Netflix",
    "디즈니플러스": "Disney+",
    "disney+": "Disney+",
    "disney plus": "Disney+",
    "디즈니": "Disney+",
    "웨이브": "Wavve",
    "wavve": "Wavve",
    # AI tools (extended)
    "미드저니": "Midjourney",
    "코파일럿": "GitHub Copilot",
    "cursor": "Cursor",
    "suno": "Suno",
    "runway": "Runway",
    "runway ml": "Runway",
}
